# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d65rzKROzo31qUoOu2sHPEixAUl2lsJD
"""

# EDIT this to whichever model performed best on your run
joblib.dump(svm, "har_model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(le, "label_encoder.pkl")

# If CNN wins instead, save it like this:
# cnn.save("har_cnn_model.h5")

print("Saved: har_model.pkl, scaler.pkl, label_encoder.pkl")
print("Download these from the Colab file browser (left sidebar) -> you need them for Step 3.")

best_preds = svm_preds   # change to rf_preds or cnn_preds if that model wins
cm = confusion_matrix(y_test_enc, best_preds)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=class_names, yticklabels=class_names)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - Best Model")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

results = {"Random Forest": rf_acc, "SVM": svm_acc, "1D-CNN": cnn_acc}
plt.figure(figsize=(6, 4))
plt.bar(results.keys(), results.values(), color=["steelblue", "seagreen", "indianred"])
plt.ylim(0.8, 1.0)
plt.ylabel("Test Accuracy")
plt.title("Model Comparison")
plt.show()
print(results)

# ============================================================
X_train_cnn = X_train_scaled.reshape(-1, X_train_scaled.shape[1], 1)
X_test_cnn  = X_test_scaled.reshape(-1, X_test_scaled.shape[1], 1)

cnn = models.Sequential([
    layers.Conv1D(64, kernel_size=5, activation="relu", input_shape=(X_train_cnn.shape[1], 1)),
    layers.MaxPooling1D(2),
    layers.Conv1D(128, kernel_size=5, activation="relu"),
    layers.MaxPooling1D(2),
    layers.Flatten(),
    layers.Dense(128, activation="relu"),
    layers.Dropout(0.4),
    layers.Dense(len(class_names), activation="softmax")
])

cnn.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
cnn.summary()

history = cnn.fit(
    X_train_cnn, y_train_enc,
    validation_split=0.15,
    epochs=20,
    batch_size=64,
    verbose=1
)

cnn_loss, cnn_acc = cnn.evaluate(X_test_cnn, y_test_enc, verbose=0)
cnn_preds = np.argmax(cnn.predict(X_test_cnn), axis=1)
print(f"\n1D-CNN Accuracy: {cnn_acc:.4f}")
print(classification_report(y_test_enc, cnn_preds, target_names=class_names))

svm = SVC(kernel="rbf", C=10, gamma="scale")
svm.fit(X_train_scaled, y_train_enc)      # SVM needs scaled features
svm_preds = svm.predict(X_test_scaled)
svm_acc = accuracy_score(y_test_enc, svm_preds)
print(f"\nSVM Accuracy: {svm_acc:.4f}")
print(classification_report(y_test_enc, svm_preds, target_names=class_names))

rf = RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1)
rf.fit(X_train, y_train_enc)              # RF doesn't need scaling
rf_preds = rf.predict(X_test)
rf_acc = accuracy_score(y_test_enc, rf_preds)
print(f"\nRandom Forest Accuracy: {rf_acc:.4f}")
print(classification_report(y_test_enc, rf_preds, target_names=class_names))

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

le = LabelEncoder()
y_train_enc = le.fit_transform(y_train["Activity"])
y_test_enc  = le.transform(y_test["Activity"])
class_names = le.classes_
print("Classes:", class_names)

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import tensorflow as tf
from tensorflow.keras import layers, models
import joblib

signal = pd.read_csv(f"{DATA_DIR}/train/Inertial Signals/body_acc_x_train.txt",
                      sep=r"\s+", header=None)
subject_labels = pd.read_csv(f"{DATA_DIR}/train/y_train.txt", header=None, names=["Activity"])
subject_labels["Activity"] = subject_labels["Activity"].map(label_map)

plt.figure(figsize=(12, 6))
for activity in subject_labels["Activity"].unique():
    idx = subject_labels[subject_labels["Activity"] == activity].index[0]
    plt.plot(signal.iloc[idx], label=activity, alpha=0.8)
plt.title("Raw Body Acceleration (X-axis) - One Window per Activity")
plt.xlabel("Time step (within a 2.56s window, 128 samples @ 50Hz)")
plt.ylabel("Acceleration")
plt.legend()
plt.show()
# Interview point: Walking/Upstairs/Downstairs show clear periodic oscillation
# (footstep cycles). Sitting/Standing/Laying are near-flat (static posture) ->
# this is WHY static postures get confused with each other but not with dynamic ones.

print("EDA complete. Save X_train, X_test, y_train, y_test — you'll reuse them in Step 2.")

sample_cols = X_train.columns[:30]
plt.figure(figsize=(12, 10))
sns.heatmap(X_train[sample_cols].corr(), cmap="coolwarm", center=0)
plt.title("Feature Correlation (first 30 features)")
plt.show()
# Interview point: many features are highly correlated (e.g., mean and std of the
# same axis across time/frequency domain) -> justifies dimensionality reduction
# (PCA) or tree-based models that handle redundant features natively.

plt.figure(figsize=(8, 4))
sns.countplot(x=y_train["Activity"], order=y_train["Activity"].value_counts().index)
plt.title("Class Distribution - Training Set")
plt.xticks(rotation=30)
plt.tight_layout()
plt.show()

y_train["Activity"] = y_train["Activity"].map(label_map)
y_test["Activity"]  = y_test["Activity"].map(label_map)

print("X_train shape:", X_train.shape)   # (7352, 561)
print("X_test shape:", X_test.shape)     # (2947, 561)
print(y_train["Activity"].value_counts())

X_train = pd.read_csv(f"{DATA_DIR}/train/X_train.txt", sep=r"\s+", header=None, names=feature_names)
X_test  = pd.read_csv(f"{DATA_DIR}/test/X_test.txt",  sep=r"\s+", header=None, names=feature_names)

y_train = pd.read_csv(f"{DATA_DIR}/train/y_train.txt", header=None, names=["Activity"])
y_test  = pd.read_csv(f"{DATA_DIR}/test/y_test.txt",  header=None, names=["Activity"])

activity_labels = pd.read_csv(f"{DATA_DIR}/activity_labels.txt", sep=r"\s+", header=None,
                               names=["id", "activity"])
label_map = dict(zip(activity_labels.id, activity_labels.activity))

features = pd.read_csv(f"{DATA_DIR}/features.txt", sep=r"\s+", header=None, names=["idx", "feature"])
feature_names = features["feature"].tolist()

# UCI HAR has duplicate feature names -> make them unique to avoid pandas errors
# Manually dedupe feature names (UCI HAR has many duplicate column names)
def dedupe_names(names):
    seen = {}
    result = []
    for name in names:
        if name not in seen:
            seen[name] = 0
            result.append(name)
        else:
            seen[name] += 1
            result.append(f"{name}.{seen[name]}")
    return result

feature_names = dedupe_names(feature_names)

DATA_DIR = "har_data/UCI HAR Dataset"

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

!rm -rf har_data har.zip
!wget -q https://archive.ics.uci.edu/static/public/240/human+activity+recognition+using+smartphones.zip -O har.zip
!unzip -oq har.zip -d har_data
!unzip -oq "har_data/UCI HAR Dataset.zip" -d har_data